### ISSUE TITLE
remove_useless_points.jsx-not all points are deleted

### ISSUE THREAD

**Issue by Tungee** [colorage/illustrator_scripts#1]
First of thankyk you so much for this skript. I searched a lot for this functionality, but i have problems with the results:

![bildschirmfoto 2016-12-11 um 19 44 48](https://cloud.githubusercontent.com/assets/3286171/21082370/72cad998-bfda-11e6-9273-6a501a02bad5.png)

![bildschirmfoto 2016-12-11 um 19 45 03](https://cloud.githubusercontent.com/assets/3286171/21082369/72c9524e-bfda-11e6-8271-b0320e2ea105.png)

Best Regards

**Comment by colorage** [comment]
Hi.  Thank you. Could you send me ai file?

вс, 11 дек. 2016 г., 21:46 Tungee <notifications@github.com>:

**Comment by Tungee** [comment]
Hi Colorage, here is the file:

[testai.zip](https://github.com/colorage/illustrator_scripts/files/646702/testai.zip)
  
Best regards!

**Comment by colorage** [comment]
Tungee, It looks like it works well now. Check it by yourself. 
Thank you for bug report.

**Comment by Tungee** [comment]
Great! Now it works!
Thanky you very much!
